apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: controller:dev
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: controller-secrets
                  key: MONGO_URI
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: controller-secrets
                  key: RABBITMQ_URL
