apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: crawler:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /raw
              name: raw-volume
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: controller-secrets
                  key: RABBITMQ_URL
      volumes:
        - name: raw-volume
          persistentVolumeClaim:
            claimName: raw-shared-pvc