apiVersion: v2
name: databases
description: Helm chart que instala RabbitMQ y MongoDB como subcharts
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: rabbitmq
    version: "12.10.0"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled

  - name: mongodb
    version: "16.5.5"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled